spring:
  application:
    name: Lo2IotHub
    
kerlink:
  base-url: https://wmc-poc.wanesy.com/gms
  login: szymon.lisiecki
  password: \65~R?8yv34u
  page-size: 2
  
lo:
  api-key: 7eccf568340943278c0495654b5de320
  devices-url: https://liveobjects.orange-business.com/api/v1/deviceMgt/devices
  synchronization-device-interval: 10000
  synchronization-thread-pool-size: 40
  page-size: 1
  properties-key: platform
  properties-value: kerlink